//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemZaRegistracijuVozilaClient.SistemZaRegistracijuVozila {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vlasnik", Namespace="http://schemas.datacontract.org/2004/07/SistemZaRegistracijuVozila")]
    [System.SerializableAttribute()]
    public partial class Vlasnik : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JmbgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrezimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ime {
            get {
                return this.ImeField;
            }
            set {
                if ((object.ReferenceEquals(this.ImeField, value) != true)) {
                    this.ImeField = value;
                    this.RaisePropertyChanged("Ime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Jmbg {
            get {
                return this.JmbgField;
            }
            set {
                if ((object.ReferenceEquals(this.JmbgField, value) != true)) {
                    this.JmbgField = value;
                    this.RaisePropertyChanged("Jmbg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prezime {
            get {
                return this.PrezimeField;
            }
            set {
                if ((object.ReferenceEquals(this.PrezimeField, value) != true)) {
                    this.PrezimeField = value;
                    this.RaisePropertyChanged("Prezime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vozilo", Namespace="http://schemas.datacontract.org/2004/07/SistemZaRegistracijuVozila")]
    [System.SerializableAttribute()]
    public partial class Vozilo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BojaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BrojsasijeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarkaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Boja {
            get {
                return this.BojaField;
            }
            set {
                if ((object.ReferenceEquals(this.BojaField, value) != true)) {
                    this.BojaField = value;
                    this.RaisePropertyChanged("Boja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Brojsasije {
            get {
                return this.BrojsasijeField;
            }
            set {
                if ((this.BrojsasijeField.Equals(value) != true)) {
                    this.BrojsasijeField = value;
                    this.RaisePropertyChanged("Brojsasije");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Marka {
            get {
                return this.MarkaField;
            }
            set {
                if ((object.ReferenceEquals(this.MarkaField, value) != true)) {
                    this.MarkaField = value;
                    this.RaisePropertyChanged("Marka");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Registracija", Namespace="http://schemas.datacontract.org/2004/07/SistemZaRegistracijuVozila")]
    [System.SerializableAttribute()]
    public partial class Registracija : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RBrojRegistracijeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RDatumKrajaRegistracijeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RDatumPocetkaRegistracijeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SistemZaRegistracijuVozilaClient.SistemZaRegistracijuVozila.Vlasnik RVlasnikField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RBrojRegistracije {
            get {
                return this.RBrojRegistracijeField;
            }
            set {
                if ((this.RBrojRegistracijeField.Equals(value) != true)) {
                    this.RBrojRegistracijeField = value;
                    this.RaisePropertyChanged("RBrojRegistracije");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RDatumKrajaRegistracije {
            get {
                return this.RDatumKrajaRegistracijeField;
            }
            set {
                if ((this.RDatumKrajaRegistracijeField.Equals(value) != true)) {
                    this.RDatumKrajaRegistracijeField = value;
                    this.RaisePropertyChanged("RDatumKrajaRegistracije");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RDatumPocetkaRegistracije {
            get {
                return this.RDatumPocetkaRegistracijeField;
            }
            set {
                if ((this.RDatumPocetkaRegistracijeField.Equals(value) != true)) {
                    this.RDatumPocetkaRegistracijeField = value;
                    this.RaisePropertyChanged("RDatumPocetkaRegistracije");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SistemZaRegistracijuVozilaClient.SistemZaRegistracijuVozila.Vlasnik RVlasnik {
            get {
                return this.RVlasnikField;
            }
            set {
                if ((object.ReferenceEquals(this.RVlasnikField, value) != true)) {
                    this.RVlasnikField = value;
                    this.RaisePropertyChanged("RVlasnik");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SistemZaRegistracijuVozila.IServisZaRegistracijuVozila")]
    public interface IServisZaRegistracijuVozila {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServisZaRegistracijuVozila/RegistrujVozilo")]
        void RegistrujVozilo(SistemZaRegistracijuVozilaClient.SistemZaRegistracijuVozila.Vlasnik vlasnik, SistemZaRegistracijuVozilaClient.SistemZaRegistracijuVozila.Vozilo vozilo, System.DateTime datumKRajaRegistracije);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IServisZaRegistracijuVozila/RegistrujVozilo")]
        System.Threading.Tasks.Task RegistrujVoziloAsync(SistemZaRegistracijuVozilaClient.SistemZaRegistracijuVozila.Vlasnik vlasnik, SistemZaRegistracijuVozilaClient.SistemZaRegistracijuVozila.Vozilo vozilo, System.DateTime datumKRajaRegistracije);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServisZaRegistracijuVozila/VratiListuSvihVozila", ReplyAction="http://tempuri.org/IServisZaRegistracijuVozila/VratiListuSvihVozilaResponse")]
        SistemZaRegistracijuVozilaClient.SistemZaRegistracijuVozila.Vozilo[] VratiListuSvihVozila(SistemZaRegistracijuVozilaClient.SistemZaRegistracijuVozila.Vlasnik vlasnik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServisZaRegistracijuVozila/VratiListuSvihVozila", ReplyAction="http://tempuri.org/IServisZaRegistracijuVozila/VratiListuSvihVozilaResponse")]
        System.Threading.Tasks.Task<SistemZaRegistracijuVozilaClient.SistemZaRegistracijuVozila.Vozilo[]> VratiListuSvihVozilaAsync(SistemZaRegistracijuVozilaClient.SistemZaRegistracijuVozila.Vlasnik vlasnik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServisZaRegistracijuVozila/VratiListuSvihRegistracija", ReplyAction="http://tempuri.org/IServisZaRegistracijuVozila/VratiListuSvihRegistracijaResponse" +
            "")]
        SistemZaRegistracijuVozilaClient.SistemZaRegistracijuVozila.Registracija[] VratiListuSvihRegistracija(SistemZaRegistracijuVozilaClient.SistemZaRegistracijuVozila.Vozilo vozilo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServisZaRegistracijuVozila/VratiListuSvihRegistracija", ReplyAction="http://tempuri.org/IServisZaRegistracijuVozila/VratiListuSvihRegistracijaResponse" +
            "")]
        System.Threading.Tasks.Task<SistemZaRegistracijuVozilaClient.SistemZaRegistracijuVozila.Registracija[]> VratiListuSvihRegistracijaAsync(SistemZaRegistracijuVozilaClient.SistemZaRegistracijuVozila.Vozilo vozilo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServisZaRegistracijuVozila/VratiSvaVozilaSaRegistracijama", ReplyAction="http://tempuri.org/IServisZaRegistracijuVozila/VratiSvaVozilaSaRegistracijamaResp" +
            "onse")]
        System.Collections.Generic.Dictionary<SistemZaRegistracijuVozilaClient.SistemZaRegistracijuVozila.Vozilo, SistemZaRegistracijuVozilaClient.SistemZaRegistracijuVozila.Registracija> VratiSvaVozilaSaRegistracijama();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServisZaRegistracijuVozila/VratiSvaVozilaSaRegistracijama", ReplyAction="http://tempuri.org/IServisZaRegistracijuVozila/VratiSvaVozilaSaRegistracijamaResp" +
            "onse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<SistemZaRegistracijuVozilaClient.SistemZaRegistracijuVozila.Vozilo, SistemZaRegistracijuVozilaClient.SistemZaRegistracijuVozila.Registracija>> VratiSvaVozilaSaRegistracijamaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServisZaRegistracijuVozilaChannel : SistemZaRegistracijuVozilaClient.SistemZaRegistracijuVozila.IServisZaRegistracijuVozila, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServisZaRegistracijuVozilaClient : System.ServiceModel.ClientBase<SistemZaRegistracijuVozilaClient.SistemZaRegistracijuVozila.IServisZaRegistracijuVozila>, SistemZaRegistracijuVozilaClient.SistemZaRegistracijuVozila.IServisZaRegistracijuVozila {
        
        public ServisZaRegistracijuVozilaClient() {
        }
        
        public ServisZaRegistracijuVozilaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServisZaRegistracijuVozilaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServisZaRegistracijuVozilaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServisZaRegistracijuVozilaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void RegistrujVozilo(SistemZaRegistracijuVozilaClient.SistemZaRegistracijuVozila.Vlasnik vlasnik, SistemZaRegistracijuVozilaClient.SistemZaRegistracijuVozila.Vozilo vozilo, System.DateTime datumKRajaRegistracije) {
            base.Channel.RegistrujVozilo(vlasnik, vozilo, datumKRajaRegistracije);
        }
        
        public System.Threading.Tasks.Task RegistrujVoziloAsync(SistemZaRegistracijuVozilaClient.SistemZaRegistracijuVozila.Vlasnik vlasnik, SistemZaRegistracijuVozilaClient.SistemZaRegistracijuVozila.Vozilo vozilo, System.DateTime datumKRajaRegistracije) {
            return base.Channel.RegistrujVoziloAsync(vlasnik, vozilo, datumKRajaRegistracije);
        }
        
        public SistemZaRegistracijuVozilaClient.SistemZaRegistracijuVozila.Vozilo[] VratiListuSvihVozila(SistemZaRegistracijuVozilaClient.SistemZaRegistracijuVozila.Vlasnik vlasnik) {
            return base.Channel.VratiListuSvihVozila(vlasnik);
        }
        
        public System.Threading.Tasks.Task<SistemZaRegistracijuVozilaClient.SistemZaRegistracijuVozila.Vozilo[]> VratiListuSvihVozilaAsync(SistemZaRegistracijuVozilaClient.SistemZaRegistracijuVozila.Vlasnik vlasnik) {
            return base.Channel.VratiListuSvihVozilaAsync(vlasnik);
        }
        
        public SistemZaRegistracijuVozilaClient.SistemZaRegistracijuVozila.Registracija[] VratiListuSvihRegistracija(SistemZaRegistracijuVozilaClient.SistemZaRegistracijuVozila.Vozilo vozilo) {
            return base.Channel.VratiListuSvihRegistracija(vozilo);
        }
        
        public System.Threading.Tasks.Task<SistemZaRegistracijuVozilaClient.SistemZaRegistracijuVozila.Registracija[]> VratiListuSvihRegistracijaAsync(SistemZaRegistracijuVozilaClient.SistemZaRegistracijuVozila.Vozilo vozilo) {
            return base.Channel.VratiListuSvihRegistracijaAsync(vozilo);
        }
        
        public System.Collections.Generic.Dictionary<SistemZaRegistracijuVozilaClient.SistemZaRegistracijuVozila.Vozilo, SistemZaRegistracijuVozilaClient.SistemZaRegistracijuVozila.Registracija> VratiSvaVozilaSaRegistracijama() {
            return base.Channel.VratiSvaVozilaSaRegistracijama();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<SistemZaRegistracijuVozilaClient.SistemZaRegistracijuVozila.Vozilo, SistemZaRegistracijuVozilaClient.SistemZaRegistracijuVozila.Registracija>> VratiSvaVozilaSaRegistracijamaAsync() {
            return base.Channel.VratiSvaVozilaSaRegistracijamaAsync();
        }
    }
}
